Add MeetingBar config
Specifically one that actually works

split out the non-symlink configs

diff --git a/install b/install
--- a/install
+++ b/install
@@ -5,6 +5,31 @@ set -o errexit
 
 . scripts/helpers
 
+application_configs() {
+  step "Application configurations"
+  if [ "${TYPE}" = "work" ]; then
+    substep "MeetingBar"
+    open -g -a MeetingBar
+
+    for i in {1..100}; do
+        if [ -f ~/Library/Containers/leits.MeetingBar/Data/Library/Preferences/leits.MeetingBar.plist ]; then
+            break
+        fi
+        sleep 0.1
+        if [ "${i}" -eq 100 ]; then
+            err "Configuration failed to load ➡ exiting"
+            exit 1
+        fi
+    done
+
+    osascript -e 'quit app "MeetingBar"'
+    defaults import leits.MeetingBar ~/.fettle-it/meetingbar/leits.MeetingBar.plist
+    open -a MeetingBar
+    substep_done "MeetingBar ➡ complete"
+  fi
+  step_done "Done"
+}
+
 cleanup() {
   TYPE=
   SSHAGENT=
@@ -171,16 +196,11 @@ symlink_configs() {
       warn "Files are identical ➡ Not copied"
     fi
     substep_done "k9s ➡ complete"
-
-    substep "MeetingBar"
-    ln -sf ~/.fettle-it/meetingbar/leits.MeetingBar.plist ~/Library/Containers/leits.MeetingBar/Data/Library/Preferences/leits.MeetingBar.plist &>/dev/null
-    substep_done "Rectangle ➡ complete"
   fi
 
   substep "Rectangle"
   ln -sf  ~/.fettle-it/rectangle/RectangleConfig.json ~/Library/Application\ Support/Rectangle/RectangleConfig.json &>/dev/null
   substep_done "Rectangle ➡ complete"
-
   step_done "Done"
 }
 
@@ -193,6 +213,7 @@ main() {
   configure_ssh
   source_customisations
   symlink_configs
+  application_configs
   cleanup
   popd >/dev/null
 }
