Be stricter about linting

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -3,19 +3,12 @@
 # Fail fast
 set -o errexit
 
-# shellcheck source=../scripts/helpers
-. ./scripts/helpers
-
-CHANGED_FILES=()
-
-git status --porcelain | while read -r state file; do
-  case "${state}" in
-  A | AM | M*) CHANGED_FILES+=("${file}") ;;
-  esac
-done
-
-for file in "${CHANGED_FILES[@]}"; do
-  if head --lines 1 "${file}" | grep '#!' >/dev/null; then
-    shfmt --diff "${file}"
+for file in $(git diff --name-only); do
+  shfmt --diff -i 2 -sr -ci -w "${file}"
+  if [ $? -ne 0 ]; then
+    echo "shfmt failed on file '${file}'"
+    exit 1
+  else
+    git add "${file}"
   fi
 done
